CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ENTRY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SACK_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ITEMS_ENTRY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TB_USER (
    ID NUMBER DEFAULT USER_SEQ.NEXTVAL NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (ID)
);

CREATE TABLE TB_ENTRY(
    ID NUMBER DEFAULT ENTRY_SEQ.NEXTVAL NOT NULL,
    USER_ID NUMBER NOT NULL,
    DATA DATE NOT NULL,
    TYPE_SNACK VARCHAR(1) NOT NULL,
    CONSTRAINT PK_ENTRY PRIMARY KEY (ID),
    CONSTRAINT FK_ENTRY_USER FOREIGN KEY (USER_ID) REFERENCES TB_USER(ID)
);

CREATE TABLE TB_SACK(
    ID NUMBER DEFAULT SACK_SEQ.NEXTVAL NOT NULL,
    NAME_SNACK VARCHAR2(100) NOT NULL,
    PORTION NUMBER NOT NULL,
    QTDE_PROTEIN NUMBER NOT NULL,
    QTDE_CARBOHYDRATE NUMBER NOT NULL,
    QTDE_FAT NUMBER NOT NULL,
    QTDE_CALORIES NUMBER NOT NULL,
    CONSTRAINT PK_SACK PRIMARY KEY (ID)
);

CREATE TABLE TB_ITEMS_ENTRY(
    ID NUMBER DEFAULT ITEMS_ENTRY_SEQ.NEXTVAL NOT NULL,
    ENTRY_ID NUMBER NOT NULL,
    SNACK_ID NUMBER NOT NULL,
    PORTION NUMBER NOT NULL,
    TOTAL_CALORIES NUMBER NOT NULL,
    CONSTRAINT PK_ITEMS_ENTRY PRIMARY KEY (ID),
    CONSTRAINT FK_ITEM_ENTRY FOREIGN KEY (ENTRY_ID) REFERENCES TB_ENTRY(ID),
    CONSTRAINT FK_ITEM_SNACK FOREIGN KEY (SNACK_ID) REFERENCES TB_SACK(ID)
);

